### PR TITLE
Logo optimizations

### PR DESCRIPTION
**Pull request by tvanantwerp**
I edited the original SVG logo to remove lots of junk Inkscape threw in, to make the `< />` a series of paths rather than text elements, to eliminate white space around the logo, and to precisely position shapes and paths along a pixel grid. This brought the size from roughly 6.6kb to 1.1kb.

With the modified SVG, I regenerated the PNG files with a focus on crisp edges for straight lines (the two DC flag bars, the ends of the `<` and `>`). The 500px-wide logo went from 14kb to 6.3kb, the 100px-wide from 4.8kb to 2.2kb, and the white logo from 3.7kb to 1.1kb. Whitespace has been removed from the PNG logos.

### CODE REVIEW

**Comment by stvnrlly** [comment]
That all sounds excellent. With these changes, are there any functional differences to be aware of? It looks like the `.png` might sit slightly differently on a webpage due to the dimension change.

**Comment by tvanantwerp** [comment]
Yes, the PNGs don't include whitespace in the files themselves anymore, so they likely would appear larger and vertically shifted iif current versions were directly replaced. I generally try to avoid whitespace in graphic files themselves in favor of CSS margins/padding, but the PNGs can be regenerated with the whitespace included if it avoids lots of changes elsewhere.

**Comment by tvanantwerp** [comment]
I went ahead and remade the PNGs with the original whitespace and dimensions retained. Files are slightly larger, but only marginally.

**Comment by stvnrlly** [comment]
Taking out the whitespace is not an issue, actually, I just wanted to check the logistics of making replacements. Either way is probably fine. I'm wondering if we should re-center the flag between the brackets, but I'd defer to @mattbailey0 @leahbannon and @justgrimes on that.

**Comment by tvanantwerp** [comment]
Something I'm curious about is the choice of red for the DC flag portion of the logo. I checked with the DC government via Twitter and [they confirmed that #e81b39 is the official red](https://twitter.com/DCGovWeb/status/588410288535433216); the Code for DC logo uses #800000. I wasn't sure if there was a particular reason for the difference--I didn't mess with the colors.

**Comment by mattbailey0** [comment]
This is great! Thanks @tvanantwerp.  I'm comfortable merging these changes.  Incidentally, I wouldn't ever have other sites pull directly from this repository for exactly the reasons that @stvnrlly notes - we don't want cross-repository dependencies on visual assets.  

Re:#80000 the reasoning for that choice isn't sophisticated.  There's no need to match the official city color (we're not affiliated/could make it teal if we wanted to), and this shade confers a bit more weight and dignity than the official shade - something that Code for DC as a volunteer organization can benefit from.

**Pull request merged**
